### PR TITLE
Adding instructions for build and usage of containers

### PR DESCRIPTION
**Pull request by vsoch**
The Dockerfile (in a subfolder) isn't obviously there, so it might not be obvious that it's possible to easily use the software with containers (Docker or Singularity)! Along with testing both for the newly merged #63, I've written up clear instructions for building and using the container with Docker or Singularity. This PR has no functional changes to code, but just updates documentation to allow for easier usage.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by jdimatteo** [comment]
vsoch this is really great -- thanks for documenting this! I followed your instructions and they all worked for me -- it is great seeing Singularity seamlessly work with the local file system.

This kind of documentation has in the past been kept at https://github.com/BradnerLab/pipeline/wiki/bamliquidator , and specifically the [docker install section](https://github.com/BradnerLab/pipeline/wiki/bamliquidator#Docker).

One option would be to migrate this nice documentation to the wiki, and maybe just briefly mention container support in the README and link to the relevant section of the wiki.  Maybe we could update that wiki to highlight docker/singularity as the preferred install mechanism.  We might preserve the other apt-get based install method as an "alternate" install method, or just remove it entirely.

Another option would be to migrate the current wiki install documentation to the README, with the wiki linking to the README. This would have the benefit of version controlling the install documentation to better allow code reviews like this one.

Were you aware of the wiki? I don't have a strong preference, and I'm happy to help with either of those options and I'm open to exploring additional alternatives. I'm very grateful for you taking the time documenting this making our docker containers more usable -- please let me know how I can help.

**Comment by vsoch** [comment]
@jdimatteo - my personal observation (and opinions formed from it) is that people are less likely to look to wikis unless they are explicitly linked, and since it's technically a different repository it's hard to keep documentation in sync with code. Since the wiki already exists, I would suggest putting the documentation where the user expects to find it (in the README with the code) and then linking to that (the latest version) from the wiki.

**Comment by vsoch** [comment]
To answer your question, I was totally unaware of the wiki. I was surprised that the repository didn't seem to have any documentation, actually. Let me add a link to it in the README so the user knows to look there.

**Comment by vsoch** [comment]
And I'm happy to help with whichever you think is best - my 0.02 is that wikis associated with repos tend to be overlooked, forgotten, and go out of sync with code. Even if you cloned the wiki content and put it in a docs subfolder and then deployed that on GitHub pages, it would hugely improve finding things! I'm glad to give this a shot, let me know.

**Comment by vsoch** [comment]
I'll open another PR in a few minutes with what I have in mind, stay tuned!

**Comment by jdimatteo** [comment]
Please consider closing this PR, since it looks like #78 already includes these changes.

**Comment by vsoch** [comment]
Closing in favor of #78

**Pull request closed without merging**
